#
# Makefile for the CS 105 Synchronization Memory Homework, Spring 2020
#
# Eleanor Birrell
# Pomona College
# April 29, 2020
#


all: client server

client: imclient.c
	gcc -o client imclient.c

server: imserver.c
	gcc -o server imserver.c

clean:
	rm -rf *~
	rm -rf client
	rm -rf server


