#
# Makefile for the CS 105 Caching Homework
#
# Eleanor Birrell
# Pomona College
# February 28, 2023
#
SHELL = /bin/sh

all: caching

caching: caching.c
	gcc -g -Wall -o caching caching.c

clean:
	rm -rf caching
	rm -rf caching.dSYM
	rm -rf *~
